# -*- coding: utf-8 -*-
"""Spettrometria_sorgenti_tubo_fotoelettrico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19LRJPi9OJpuTv3TS2XHaPqFZXXDyppKF
"""

import numpy as np
from matplotlib import pyplot as plt
from numpy import genfromtxt
import pandas as pd
lam = {}

lam[430] = genfromtxt('430.csv', delimiter=',')
lam[470] = genfromtxt('470.csv', delimiter=',')
lam[540] = genfromtxt('540.csv', delimiter=',')
lam[612] = genfromtxt('612.csv', delimiter=',')
lam[644] = genfromtxt('644.csv', delimiter=',')

fig, ax = plt.subplots()
ax.plot(lam[430].transpose()[0], lam[430].transpose()[1], label="$\lambda_m$ =430 nm", c="violet")
ax.plot(lam[470].transpose()[0], lam[470].transpose()[1], label="$\lambda_m$ =470 nm", c="blue")
ax.plot(lam[540].transpose()[0], lam[540].transpose()[1], label="$\lambda_m$ =540 nm", c="yellowgreen")
ax.plot(lam[612].transpose()[0], lam[612].transpose()[1], label="$\lambda_m$ =612 nm", c="orangered")
ax.plot(lam[644].transpose()[0], lam[644].transpose()[1], label="$\lambda_m$ =644 nm", c="red")
plt.legend()
plt.grid()
plt.xlabel("Lunghezza d'onda $\lambda$ [nm]")
plt.ylabel("Intensità relativa (conteggi ADC)")
plt.title("Spettro di emissione delle sorgenti LED")
plt.savefig("spectrum.pdf")

lam[430]

lam[470]

import plotly.express as px
fig = px.scatter(x=lam[612].transpose()[0], y=lam[612].transpose()[1])
fig.show()

